### PR TITLE
upstream a cleaned version of MPI allreduce benchmark

### PR DESCRIPTION
**Pull request by lgarithm**
add mpi allreduce benchmark

### CODE REVIEW

**Comment by lgarithm** [comment]
Hi @csegarragonz, could you run the github action to see if this breaks the CI, thanks.

**Comment by csegarragonz** [comment]
@lgarithm there seems to be a problem with the permissions when I approve your run, i'll take a look

**Comment by csegarragonz** [comment]
it [seems](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow) that gha secrets are not passed to runners running a fork of the repo.

truth is that we do not really need the secrets for the main tests workflow, as we are only pulling from ACR.
we still need them for release workflows, but that's ok.

hopefully #392 fixes this.

**Comment by csegarragonz** [comment]
@lgarithm could you rebase to the latest `main`?

**Comment by lgarithm** [comment]
@csegarragonz I pushed the rebase.

**Comment by csegarragonz** [comment]
@lgarithm this is looking good.

can you rebase again (forgot to remove another usage of secrets), and then run:

```
inv format-code
```

(from _inside_ the container) to format the c++ code?

**Pull request merged**
