### PR TITLE
wip: test transport layer improvements

### PR DESCRIPTION
**Pull request by csegarragonz**
This PR combines:
* spinlock queue for mpi: #385 
* c-struct for mpi messages: #379
* mimalloc memory allocator: #387 (this seems to not improve our benchmarks)
* transport layer improvements:
  *  c-struct for ptp messages: #388

we will merge them separately, but ideally we want to have both PRs above green, and then measure the benefits (hopefully we are on par with #382)

### CODE REVIEW

**Comment by lgarithm** [comment]
```
BGN ========================================bench_allreduce========================================
bench_all_reduce(np=4) took 0.0354s, total workload: 3.662MiB, rate: 0.101GiB/s
bench_all_reduce(np=4) took 0.0319s, total workload: 3.662MiB, rate: 0.112GiB/s
bench_all_reduce(np=4) took 0.0316s, total workload: 3.662MiB, rate: 0.113GiB/s
bench_all_reduce(np=4) took 0.0319s, total workload: 3.662MiB, rate: 0.112GiB/s
bench_all_reduce(np=4) took 0.0321s, total workload: 3.662MiB, rate: 0.112GiB/s
bench_all_reduce(np=4) took 0.0328s, total workload: 3.662MiB, rate: 0.109GiB/s
bench_all_reduce(np=4) took 0.0317s, total workload: 3.662MiB, rate: 0.113GiB/s
bench_all_reduce(np=4) took 0.0316s, total workload: 3.662MiB, rate: 0.113GiB/s
bench_all_reduce(np=4) took 0.0314s, total workload: 3.662MiB, rate: 0.114GiB/s
bench_all_reduce(np=4) took 0.0315s, total workload: 3.662MiB, rate: 0.113GiB/s
bench_all_reduce(np=4) took 0.2235s, total workload: 1.144GiB, rate: 5.117GiB/s
bench_all_reduce(np=4) took 0.2024s, total workload: 1.144GiB, rate: 5.652GiB/s
bench_all_reduce(np=4) took 0.2050s, total workload: 1.144GiB, rate: 5.579GiB/s
bench_all_reduce(np=4) took 0.2047s, total workload: 1.144GiB, rate: 5.586GiB/s
bench_all_reduce(np=4) took 0.2059s, total workload: 1.144GiB, rate: 5.556GiB/s
bench_all_reduce(np=4) took 0.2053s, total workload: 1.144GiB, rate: 5.570GiB/s
bench_all_reduce(np=4) took 0.2055s, total workload: 1.144GiB, rate: 5.565GiB/s
bench_all_reduce(np=4) took 0.2045s, total workload: 1.144GiB, rate: 5.594GiB/s
bench_all_reduce(np=4) took 0.2030s, total workload: 1.144GiB, rate: 5.633GiB/s
bench_all_reduce(np=4) took 0.2067s, total workload: 1.144GiB, rate: 5.533GiB/s
END ========================================bench_allreduce========================================
```

**Comment by lgarithm** [comment]
what's the difference of this PR and #382?

**Comment by lgarithm** [comment]
looks like it is on par with #382. What's their difference?

**Comment by csegarragonz** [comment]
@lgarithm that is great news! this PR is meant to be the same than #382 but is just a pure merge of #385 and #379 (both passing all the tests)

so before merging both of them i wanted to make sure that in the upstreaming process i did not mess up in any way

**Comment by csegarragonz** [comment]
@lgarithm could you run the benchmarks with the latest commit i have added and include the results where it says `PASTE HERE` in the message above? (i have edited it slightly)

note that i've cleaned-up the commit history to make sure we know which commit introduces what, so this may affect your merging/rebasing.

**Pull request closed without merging**
